### ISSUE TITLE
Implement "logical_disk" collector

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-windows-exporter#7]
Prometheus' Windows Exporter

* https://github.com/prometheus-community/windows_exporter/blob/master/collector/logical_disk.go
* https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.logical_disk.md

**Comment by daipom** [comment]
The data of `free_bytes` and `total_bytes` needs attention.

This uses `% Free Space_Base` for the counter name, but that name doesn't exist.

* https://github.com/prometheus-community/windows_exporter/blob/master/collector/logical_disk.go#L180
* LogicalDisk Object: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc784596(v=ws.10)

In fact, this name is created by the windows_exporter: https://github.com/prometheus-community/windows_exporter/blob/master/collector/perflib.go#L56-L62

This is based on the specification of Windows Performance Counter.
Some counter types have multiple counters with the same name.
Therefore, in order to have a counter in a hash, we need to do something like [this](https://github.com/prometheus-community/windows_exporter/blob/master/collector/perflib.go#L56-L62).

`IsBaseValue` is created by perflib: https://github.com/leoluk/perflib_exporter/blob/master/perflib/perflib.go#L360-L362

`CounterType`: 
* https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc785636(v=ws.10)
* https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.performancecountertype?view=dotnet-plat-ext-6.0#System_Diagnostics_PerformanceCounterType_RawFraction

In this case, `LogicalDisk` object has 2 `% Free Space`  counter definitions.

* CounterType: 537003008 (0x20020400)
   * `RawFraction` type: 
     * The numerator value.
     * In this case this means free space of the column, the same as `Free Megabytes` value.
* CounterType: 1073939459 (0x40030403)
  * `RawBase` type: 
    * The denominator value.
    * In this case this means total space of the volume.

After all, the data of `free_bytes` and `total_bytes` are following.

* `free_bytes`: `Free Megabytes` counter
* `total_bytes`: `% Free Space_Base` i.e. type `RawBase` of `% Free Space` counter

In prometheous windows_exporter, the label names are reversed. (No problem with the behavior.)
We should feedback this.

* https://github.com/prometheus-community/windows_exporter/blob/master/collector/logical_disk.go#L180-L181

**Comment by daipom** [comment]
Implemented a initial working version at fc12d5fe8ecec305d0b8ec67e98e4f1eef394b81.

Some values are not correct because of https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/issues/1#issuecomment-994297022.

**Comment by fujimotos** [comment]
@daipom OK. I can confirm that the disk metrics is now flowing on WIndows Server 2022.
Here is how it looks like on my machine:

```
2021-12-15 06:20:24.379554300 +0000 test.log: {"type":"counter","name":"windows_logical_disk_reads_total","desc":"Rate of read operations on the disk","labels":{"volumn":"D:"},"value":1539}
2021-12-15 06:20:24.379554300 +0000 test.log: {"type":"counter","name":"windows_logical_disk_write_bytes_total","desc":"Rate at which bytes are transferred to the disk during write operations","labels":{"volumn":"D:"},"value":454316032}
2021-12-15 06:20:24.379554300 +0000 test.log: {"type":"counter","name":"windows_logical_disk_writes_total","desc":"Rate of write operations on the disk","labels":{"volumn":"D:"},"value":3105}
```

**Comment by daipom** [comment]
@fujimotos  Thank you!
After https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/issues/1#issuecomment-994297022 is implemented, I will check value correctness.

**Comment by daipom** [comment]
https://github.com/fluent-plugins-nursery/fluent-plugin-windows-exporter/issues/1#issuecomment-994297022 has been implemented.

And I have checked this can get the expected values.
